const Help = () => {
  return (
    <div className="px-6 py-8 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-6 text-center">Privacy Policy</h1>

      <p className="text-lg mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="text-lg mb-6">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{' '}
        <a
          href="https://www.termsfeed.com/privacy-policy-generator/"
          target="_blank"
          className="text-blue-600 hover:underline"
        >
          Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Interpretation and Definitions
      </h2>
      <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
      <p className="mb-4 text-lg">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold mb-2">Definitions</h3>
      <ul className="list-inside list-disc space-y-3">
        <li className="text-lg">
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li className="text-lg">
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li className="text-lg">
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to MeetUpNow.
        </li>
        <li className="text-lg">
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li className="text-lg">
          <strong>Country</strong> refers to: United Kingdom
        </li>
        <li className="text-lg">
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li className="text-lg">
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li className="text-lg">
          <strong>Service</strong> refers to the Website.
        </li>
        <li className="text-lg">
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li className="text-lg">
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li className="text-lg">
          <strong>Website</strong> refers to MeetUpNow, accessible from{' '}
          <a
            href="https://xiaoru-sun.github.io/MeetUpInReactJS/"
            target="_blank"
            className="text-blue-600 hover:underline"
          >
            https://xiaoru-sun.github.io/MeetUpInReactJS/
          </a>
        </li>
        <li className="text-lg">
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:{' '}
        <span className="font-semibold">Email address, Usage Data</span>
      </p>

      <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
      <p className="mb-4">
        Usage Data is collected automatically when using the Service. This can
        include things like your device's IP address, browser type, pages
        visited, and more.
      </p>

      <h4 className="text-lg font-semibold mb-2">
        Tracking Technologies and Cookies
      </h4>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. These include technologies
        such as beacons, tags, and scripts.
      </p>

      <ul className="list-inside list-disc space-y-3">
        <li className="text-lg">
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file
          placed on Your Device. You can refuse all Cookies, but doing so may
          limit your ability to use some parts of the Service.
        </li>
        <li className="text-lg">
          <strong>Web Beacons:</strong> These are small electronic files used
          for tracking users and other related statistics.
        </li>
      </ul>

      <p className="text-lg mb-4">
        We use both Session and Persistent Cookies for the following purposes:
      </p>

      <ul className="list-inside list-disc space-y-3">
        <li className="text-lg">
          <strong>Necessary / Essential Cookies:</strong> These are required to
          provide You with the service and enable essential features like login.
        </li>
        <li className="text-lg">
          <strong>Cookies Policy / Notice Acceptance Cookies:</strong> These
          track if users have accepted the use of cookies.
        </li>
        <li className="text-lg">
          <strong>Functionality Cookies:</strong> These help us remember your
          preferences and make your experience more personal.
        </li>
      </ul>

      <p className="mb-6 text-lg">
        For more information about the cookies we use and your choices regarding
        cookies, please visit our{' '}
        <span className="font-semibold">Cookies Policy</span> section.
      </p>

      <h3 className="text-xl font-semibold mb-4">Use of Your Personal Data</h3>
      <p className="text-lg">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-inside list-disc space-y-3">
        <li className="text-lg">
          <strong>To provide and maintain our Service:</strong> This includes
          monitoring usage.
        </li>
        <li className="text-lg">
          <strong>To manage Your Account:</strong> We use your data to manage
          your registration and grant access to the service's features.
        </li>
        <li className="text-lg">
          <strong>For the performance of a contract:</strong> We fulfill
          contracts for purchases or services you request.
        </li>
        <li className="text-lg">
          <strong>To contact You:</strong> We may send notifications about
          updates or changes to the service.
        </li>
        <li className="text-lg">
          <strong>To provide You with news:</strong> Updates about new services,
          offers, and events that may interest you.
        </li>
        <li className="text-lg">
          <strong>For business transfers:</strong> If we merge or sell assets,
          your information may be shared.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mb-4">
        Retention of Your Personal Data
      </h3>
      <p className="text-lg mb-6">
        We will retain Your Personal Data only for as long as necessary for the
        purposes outlined in this Privacy Policy. If you need to delete your
        personal information, please contact us.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">
        Changes to this Privacy Policy
      </h2>
      <p className="text-lg mb-4">
        We may update Our Privacy Policy from time to time. Changes will be
        communicated through the service or via email.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p className="text-lg">
        If you have any questions about this Privacy Policy, please contact us
        at:
      </p>
      <ul className="list-inside list-disc space-y-3">
        <li className="text-lg">
          <strong>Email:</strong> camilledpp.work@gmail.com
        </li>
      </ul>
    </div>
  );
};

export default Help;
